version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=beneficios_db
      - POSTGRES_USER=beneficios_user
      - POSTGRES_PASSWORD=beneficios_pass

  web:
    build: ../backend_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend_api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://beneficios_user:beneficios_pass@db:5432/beneficios_db

volumes:
  postgres_data:
